/*
Generated by Yara-Rules
On 30-03-2020
*/
include "./kth/api_keys.yar"
include "./kth/base64.yar"
include "./kth/certificates.yar"
include "./kth/core_keywords.yar"
include "./kth/crypto_address.yar"
include "./kth/CryptoExchangeApi.yar"
include "./kth/database.yar"
include "./kth/email_filter.yar"
include "./kth/general.yar"
include "./kth/hak5.yar"
include "./kth/password_leak.yar"
